// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _KeccakP1600_Permute_s_HH_
#define _KeccakP1600_Permute_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "theta.h"
#include "chi.h"
#include "pi.h"
#include "KeccakP1600_Permucud.h"
#include "KeccakP1600_PermudEe.h"
#include "KeccakP1600_PermueOg.h"

namespace ap_rtl {

struct KeccakP1600_Permute_s : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<8> > state_address0;
    sc_out< sc_logic > state_ce0;
    sc_out< sc_logic > state_we0;
    sc_out< sc_lv<8> > state_d0;
    sc_in< sc_lv<8> > state_q0;


    // Module declarations
    KeccakP1600_Permute_s(sc_module_name name);
    SC_HAS_PROCESS(KeccakP1600_Permute_s);

    ~KeccakP1600_Permute_s();

    sc_trace_file* mVcdFile;

    KeccakP1600_Permucud* KeccakRhoOffsets_U;
    KeccakP1600_PermudEe* KeccakRoundConstants_U;
    KeccakP1600_PermueOg* stateAsWords_U;
    theta* grp_theta_fu_225;
    chi* grp_chi_fu_230;
    pi* grp_pi_fu_235;
    sc_signal< sc_lv<18> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<5> > KeccakRhoOffsets_address0;
    sc_signal< sc_logic > KeccakRhoOffsets_ce0;
    sc_signal< sc_lv<6> > KeccakRhoOffsets_q0;
    sc_signal< sc_lv<5> > KeccakRoundConstants_address0;
    sc_signal< sc_logic > KeccakRoundConstants_ce0;
    sc_signal< sc_lv<64> > KeccakRoundConstants_q0;
    sc_signal< sc_lv<5> > i_37_fu_246_p2;
    sc_signal< sc_lv<5> > i_37_reg_538;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<5> > stateAsWords_addr_1_reg_543;
    sc_signal< sc_lv<1> > icmp_ln269_fu_240_p2;
    sc_signal< sc_lv<8> > shl_ln_fu_257_p3;
    sc_signal< sc_lv<8> > shl_ln_reg_548;
    sc_signal< sc_lv<4> > j_fu_275_p2;
    sc_signal< sc_lv<4> > j_reg_562;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln271_fu_269_p2;
    sc_signal< sc_lv<5> > i_38_fu_330_p2;
    sc_signal< sc_lv<5> > i_38_reg_575;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<3> > x_fu_342_p2;
    sc_signal< sc_lv<3> > x_reg_583;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<4> > zext_ln353_fu_348_p1;
    sc_signal< sc_lv<4> > zext_ln353_reg_588;
    sc_signal< sc_lv<1> > icmp_ln352_fu_336_p2;
    sc_signal< sc_lv<3> > y_fu_358_p2;
    sc_signal< sc_lv<3> > y_reg_596;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<1> > icmp_ln352_1_fu_352_p2;
    sc_signal< sc_lv<1> > icmp_ln353_fu_397_p2;
    sc_signal< sc_lv<1> > icmp_ln353_reg_606;
    sc_signal< sc_lv<5> > stateAsWords_addr_3_reg_611;
    sc_signal< sc_lv<64> > select_ln353_fu_439_p3;
    sc_signal< sc_lv<64> > select_ln353_reg_616;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<5> > i_fu_464_p2;
    sc_signal< sc_lv<5> > i_reg_629;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<1> > icmp_ln280_fu_458_p2;
    sc_signal< sc_lv<8> > shl_ln6_fu_475_p3;
    sc_signal< sc_lv<8> > shl_ln6_reg_639;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<64> > stateAsWords_q0;
    sc_signal< sc_lv<64> > stateAsWords_load_1_reg_644;
    sc_signal< sc_lv<4> > j_19_fu_493_p2;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_lv<5> > stateAsWords_address0;
    sc_signal< sc_logic > stateAsWords_ce0;
    sc_signal< sc_logic > stateAsWords_we0;
    sc_signal< sc_lv<64> > stateAsWords_d0;
    sc_signal< sc_lv<5> > stateAsWords_address1;
    sc_signal< sc_logic > stateAsWords_ce1;
    sc_signal< sc_logic > stateAsWords_we1;
    sc_signal< sc_lv<64> > stateAsWords_d1;
    sc_signal< sc_lv<64> > stateAsWords_q1;
    sc_signal< sc_logic > grp_theta_fu_225_ap_start;
    sc_signal< sc_logic > grp_theta_fu_225_ap_done;
    sc_signal< sc_logic > grp_theta_fu_225_ap_idle;
    sc_signal< sc_logic > grp_theta_fu_225_ap_ready;
    sc_signal< sc_lv<5> > grp_theta_fu_225_A_address0;
    sc_signal< sc_logic > grp_theta_fu_225_A_ce0;
    sc_signal< sc_logic > grp_theta_fu_225_A_we0;
    sc_signal< sc_lv<64> > grp_theta_fu_225_A_d0;
    sc_signal< sc_logic > grp_chi_fu_230_ap_start;
    sc_signal< sc_logic > grp_chi_fu_230_ap_done;
    sc_signal< sc_logic > grp_chi_fu_230_ap_idle;
    sc_signal< sc_logic > grp_chi_fu_230_ap_ready;
    sc_signal< sc_lv<5> > grp_chi_fu_230_A_address0;
    sc_signal< sc_logic > grp_chi_fu_230_A_ce0;
    sc_signal< sc_lv<5> > grp_chi_fu_230_A_address1;
    sc_signal< sc_logic > grp_chi_fu_230_A_ce1;
    sc_signal< sc_logic > grp_chi_fu_230_A_we1;
    sc_signal< sc_lv<64> > grp_chi_fu_230_A_d1;
    sc_signal< sc_logic > grp_pi_fu_235_ap_start;
    sc_signal< sc_logic > grp_pi_fu_235_ap_done;
    sc_signal< sc_logic > grp_pi_fu_235_ap_idle;
    sc_signal< sc_logic > grp_pi_fu_235_ap_ready;
    sc_signal< sc_lv<5> > grp_pi_fu_235_A_address0;
    sc_signal< sc_logic > grp_pi_fu_235_A_ce0;
    sc_signal< sc_logic > grp_pi_fu_235_A_we0;
    sc_signal< sc_lv<64> > grp_pi_fu_235_A_d0;
    sc_signal< sc_lv<5> > i_0_i_reg_145;
    sc_signal< sc_lv<4> > j_0_i_reg_156;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<5> > indexRound_assign_reg_168;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<3> > x_0_i_reg_180;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<3> > y_0_i_reg_191;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<5> > i_0_i3_reg_202;
    sc_signal< sc_lv<1> > icmp_ln281_fu_487_p2;
    sc_signal< sc_lv<1> > icmp_ln293_fu_324_p2;
    sc_signal< sc_lv<4> > j_0_i5_reg_214;
    sc_signal< sc_logic > grp_theta_fu_225_ap_start_reg;
    sc_signal< sc_logic > grp_chi_fu_230_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_logic > grp_pi_fu_235_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<64> > zext_ln270_fu_252_p1;
    sc_signal< sc_lv<64> > zext_ln272_fu_286_p1;
    sc_signal< sc_lv<64> > zext_ln353_3_fu_391_p1;
    sc_signal< sc_lv<64> > zext_ln382_fu_446_p1;
    sc_signal< sc_lv<64> > zext_ln282_fu_470_p1;
    sc_signal< sc_lv<64> > zext_ln282_2_fu_530_p1;
    sc_signal< sc_lv<64> > or_ln272_fu_317_p2;
    sc_signal< sc_lv<64> > xor_ln382_fu_451_p2;
    sc_signal< sc_lv<8> > zext_ln271_fu_265_p1;
    sc_signal< sc_lv<8> > add_ln272_fu_281_p2;
    sc_signal< sc_lv<3> > trunc_ln272_fu_295_p1;
    sc_signal< sc_lv<6> > shl_ln272_1_fu_299_p3;
    sc_signal< sc_lv<64> > zext_ln272_1_fu_291_p1;
    sc_signal< sc_lv<64> > zext_ln272_2_fu_307_p1;
    sc_signal< sc_lv<64> > shl_ln272_fu_311_p2;
    sc_signal< sc_lv<4> > zext_ln353_1_fu_364_p1;
    sc_signal< sc_lv<4> > add_ln353_fu_376_p2;
    sc_signal< sc_lv<5> > shl_ln7_fu_368_p3;
    sc_signal< sc_lv<5> > zext_ln353_2_fu_381_p1;
    sc_signal< sc_lv<5> > add_ln353_1_fu_385_p2;
    sc_signal< sc_lv<64> > zext_ln353_5_fu_407_p1;
    sc_signal< sc_lv<7> > zext_ln353_4_fu_403_p1;
    sc_signal< sc_lv<7> > sub_ln353_fu_417_p2;
    sc_signal< sc_lv<64> > zext_ln353_6_fu_423_p1;
    sc_signal< sc_lv<64> > lshr_ln353_fu_427_p2;
    sc_signal< sc_lv<64> > shl_ln353_fu_411_p2;
    sc_signal< sc_lv<64> > xor_ln353_fu_433_p2;
    sc_signal< sc_lv<3> > trunc_ln282_fu_499_p1;
    sc_signal< sc_lv<6> > shl_ln282_1_fu_503_p3;
    sc_signal< sc_lv<64> > zext_ln282_1_fu_511_p1;
    sc_signal< sc_lv<64> > lshr_ln282_fu_515_p2;
    sc_signal< sc_lv<8> > zext_ln281_fu_483_p1;
    sc_signal< sc_lv<8> > add_ln282_fu_525_p2;
    sc_signal< sc_lv<18> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<18> ap_ST_fsm_state1;
    static const sc_lv<18> ap_ST_fsm_state2;
    static const sc_lv<18> ap_ST_fsm_state3;
    static const sc_lv<18> ap_ST_fsm_state4;
    static const sc_lv<18> ap_ST_fsm_state5;
    static const sc_lv<18> ap_ST_fsm_state6;
    static const sc_lv<18> ap_ST_fsm_state7;
    static const sc_lv<18> ap_ST_fsm_state8;
    static const sc_lv<18> ap_ST_fsm_state9;
    static const sc_lv<18> ap_ST_fsm_state10;
    static const sc_lv<18> ap_ST_fsm_state11;
    static const sc_lv<18> ap_ST_fsm_state12;
    static const sc_lv<18> ap_ST_fsm_state13;
    static const sc_lv<18> ap_ST_fsm_state14;
    static const sc_lv<18> ap_ST_fsm_state15;
    static const sc_lv<18> ap_ST_fsm_state16;
    static const sc_lv<18> ap_ST_fsm_state17;
    static const sc_lv<18> ap_ST_fsm_state18;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<5> ap_const_lv5_19;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<5> ap_const_lv5_18;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<7> ap_const_lv7_40;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_KeccakRhoOffsets_address0();
    void thread_KeccakRhoOffsets_ce0();
    void thread_KeccakRoundConstants_address0();
    void thread_KeccakRoundConstants_ce0();
    void thread_add_ln272_fu_281_p2();
    void thread_add_ln282_fu_525_p2();
    void thread_add_ln353_1_fu_385_p2();
    void thread_add_ln353_fu_376_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_chi_fu_230_ap_start();
    void thread_grp_pi_fu_235_ap_start();
    void thread_grp_theta_fu_225_ap_start();
    void thread_i_37_fu_246_p2();
    void thread_i_38_fu_330_p2();
    void thread_i_fu_464_p2();
    void thread_icmp_ln269_fu_240_p2();
    void thread_icmp_ln271_fu_269_p2();
    void thread_icmp_ln280_fu_458_p2();
    void thread_icmp_ln281_fu_487_p2();
    void thread_icmp_ln293_fu_324_p2();
    void thread_icmp_ln352_1_fu_352_p2();
    void thread_icmp_ln352_fu_336_p2();
    void thread_icmp_ln353_fu_397_p2();
    void thread_j_19_fu_493_p2();
    void thread_j_fu_275_p2();
    void thread_lshr_ln282_fu_515_p2();
    void thread_lshr_ln353_fu_427_p2();
    void thread_or_ln272_fu_317_p2();
    void thread_select_ln353_fu_439_p3();
    void thread_shl_ln272_1_fu_299_p3();
    void thread_shl_ln272_fu_311_p2();
    void thread_shl_ln282_1_fu_503_p3();
    void thread_shl_ln353_fu_411_p2();
    void thread_shl_ln6_fu_475_p3();
    void thread_shl_ln7_fu_368_p3();
    void thread_shl_ln_fu_257_p3();
    void thread_stateAsWords_address0();
    void thread_stateAsWords_address1();
    void thread_stateAsWords_ce0();
    void thread_stateAsWords_ce1();
    void thread_stateAsWords_d0();
    void thread_stateAsWords_d1();
    void thread_stateAsWords_we0();
    void thread_stateAsWords_we1();
    void thread_state_address0();
    void thread_state_ce0();
    void thread_state_d0();
    void thread_state_we0();
    void thread_sub_ln353_fu_417_p2();
    void thread_trunc_ln272_fu_295_p1();
    void thread_trunc_ln282_fu_499_p1();
    void thread_x_fu_342_p2();
    void thread_xor_ln353_fu_433_p2();
    void thread_xor_ln382_fu_451_p2();
    void thread_y_fu_358_p2();
    void thread_zext_ln270_fu_252_p1();
    void thread_zext_ln271_fu_265_p1();
    void thread_zext_ln272_1_fu_291_p1();
    void thread_zext_ln272_2_fu_307_p1();
    void thread_zext_ln272_fu_286_p1();
    void thread_zext_ln281_fu_483_p1();
    void thread_zext_ln282_1_fu_511_p1();
    void thread_zext_ln282_2_fu_530_p1();
    void thread_zext_ln282_fu_470_p1();
    void thread_zext_ln353_1_fu_364_p1();
    void thread_zext_ln353_2_fu_381_p1();
    void thread_zext_ln353_3_fu_391_p1();
    void thread_zext_ln353_4_fu_403_p1();
    void thread_zext_ln353_5_fu_407_p1();
    void thread_zext_ln353_6_fu_423_p1();
    void thread_zext_ln353_fu_348_p1();
    void thread_zext_ln382_fu_446_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
