// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "KeccakWidth1600_Spon_8.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic KeccakWidth1600_Spon_8::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic KeccakWidth1600_Spon_8::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> KeccakWidth1600_Spon_8::ap_ST_fsm_state1 = "1";
const sc_lv<10> KeccakWidth1600_Spon_8::ap_ST_fsm_state2 = "10";
const sc_lv<10> KeccakWidth1600_Spon_8::ap_ST_fsm_state3 = "100";
const sc_lv<10> KeccakWidth1600_Spon_8::ap_ST_fsm_state4 = "1000";
const sc_lv<10> KeccakWidth1600_Spon_8::ap_ST_fsm_state5 = "10000";
const sc_lv<10> KeccakWidth1600_Spon_8::ap_ST_fsm_state6 = "100000";
const sc_lv<10> KeccakWidth1600_Spon_8::ap_ST_fsm_state7 = "1000000";
const sc_lv<10> KeccakWidth1600_Spon_8::ap_ST_fsm_state8 = "10000000";
const sc_lv<10> KeccakWidth1600_Spon_8::ap_ST_fsm_state9 = "100000000";
const sc_lv<10> KeccakWidth1600_Spon_8::ap_ST_fsm_state10 = "1000000000";
const sc_lv<32> KeccakWidth1600_Spon_8::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> KeccakWidth1600_Spon_8::ap_const_lv32_1 = "1";
const sc_lv<1> KeccakWidth1600_Spon_8::ap_const_lv1_1 = "1";
const sc_lv<1> KeccakWidth1600_Spon_8::ap_const_lv1_0 = "0";
const sc_lv<32> KeccakWidth1600_Spon_8::ap_const_lv32_3 = "11";
const sc_lv<32> KeccakWidth1600_Spon_8::ap_const_lv32_5 = "101";
const sc_lv<32> KeccakWidth1600_Spon_8::ap_const_lv32_6 = "110";
const sc_lv<32> KeccakWidth1600_Spon_8::ap_const_lv32_9 = "1001";
const sc_lv<64> KeccakWidth1600_Spon_8::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> KeccakWidth1600_Spon_8::ap_const_lv32_4 = "100";
const sc_lv<8> KeccakWidth1600_Spon_8::ap_const_lv8_0 = "00000000";
const sc_lv<32> KeccakWidth1600_Spon_8::ap_const_lv32_2 = "10";
const sc_lv<32> KeccakWidth1600_Spon_8::ap_const_lv32_7 = "111";
const sc_lv<32> KeccakWidth1600_Spon_8::ap_const_lv32_8 = "1000";
const sc_lv<34> KeccakWidth1600_Spon_8::ap_const_lv34_0 = "0000000000000000000000000000000000";
const sc_lv<32> KeccakWidth1600_Spon_8::ap_const_lv32_21 = "100001";
const sc_lv<33> KeccakWidth1600_Spon_8::ap_const_lv33_0 = "000000000000000000000000000000000";
const sc_lv<30> KeccakWidth1600_Spon_8::ap_const_lv30_A8 = "10101000";
const sc_lv<30> KeccakWidth1600_Spon_8::ap_const_lv30_2 = "10";
const sc_lv<34> KeccakWidth1600_Spon_8::ap_const_lv34_2 = "10";
const sc_lv<2> KeccakWidth1600_Spon_8::ap_const_lv2_2 = "10";
const sc_lv<32> KeccakWidth1600_Spon_8::ap_const_lv32_A8 = "10101000";
const sc_lv<64> KeccakWidth1600_Spon_8::ap_const_lv64_A8 = "10101000";
const sc_lv<8> KeccakWidth1600_Spon_8::ap_const_lv8_A8 = "10101000";
const sc_lv<8> KeccakWidth1600_Spon_8::ap_const_lv8_1 = "1";
const sc_lv<64> KeccakWidth1600_Spon_8::ap_const_lv64_FFFFFFFFFFFFFF58 = "1111111111111111111111111111111111111111111111111111111101011000";
const bool KeccakWidth1600_Spon_8::ap_const_boolean_1 = true;

KeccakWidth1600_Spon_8::KeccakWidth1600_Spon_8(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_KeccakP1600_Permute_s_fu_163 = new KeccakP1600_Permute_s("grp_KeccakP1600_Permute_s_fu_163");
    grp_KeccakP1600_Permute_s_fu_163->ap_clk(ap_clk);
    grp_KeccakP1600_Permute_s_fu_163->ap_rst(ap_rst);
    grp_KeccakP1600_Permute_s_fu_163->ap_start(grp_KeccakP1600_Permute_s_fu_163_ap_start);
    grp_KeccakP1600_Permute_s_fu_163->ap_done(grp_KeccakP1600_Permute_s_fu_163_ap_done);
    grp_KeccakP1600_Permute_s_fu_163->ap_idle(grp_KeccakP1600_Permute_s_fu_163_ap_idle);
    grp_KeccakP1600_Permute_s_fu_163->ap_ready(grp_KeccakP1600_Permute_s_fu_163_ap_ready);
    grp_KeccakP1600_Permute_s_fu_163->state_address0(grp_KeccakP1600_Permute_s_fu_163_state_address0);
    grp_KeccakP1600_Permute_s_fu_163->state_ce0(grp_KeccakP1600_Permute_s_fu_163_state_ce0);
    grp_KeccakP1600_Permute_s_fu_163->state_we0(grp_KeccakP1600_Permute_s_fu_163_state_we0);
    grp_KeccakP1600_Permute_s_fu_163->state_d0(grp_KeccakP1600_Permute_s_fu_163_state_d0);
    grp_KeccakP1600_Permute_s_fu_163->state_q0(instance_state_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln195_fu_220_p2);
    sensitive << ( trunc_ln195_fu_216_p1 );

    SC_METHOD(thread_add_ln214_fu_374_p2);
    sensitive << ( p_1_rec_reg_115 );

    SC_METHOD(thread_add_ln224_fu_263_p2);
    sensitive << ( instance_byteIOIndex_fu_56 );
    sensitive << ( zext_ln223_fu_259_p1 );

    SC_METHOD(thread_add_ln232_fu_391_p2);
    sensitive << ( loop_1_reg_139 );
    sensitive << ( instance_byteIOIndex_fu_56 );

    SC_METHOD(thread_add_ln236_fu_402_p2);
    sensitive << ( select_ln224_reg_493 );
    sensitive << ( instance_byteIOIndex_fu_56 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln194_fu_204_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln194_fu_204_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln194_fu_204_p2 );
    sensitive << ( instance_byteIOIndex_fu_56 );

    SC_METHOD(thread_grp_KeccakP1600_Permute_s_fu_163_ap_start);
    sensitive << ( grp_KeccakP1600_Permute_s_fu_163_ap_start_reg );

    SC_METHOD(thread_i_fu_297_p2);
    sensitive << ( i_22_fu_52 );
    sensitive << ( zext_ln229_1_fu_293_p1 );

    SC_METHOD(thread_icmp_ln194_fu_204_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_194_p4 );

    SC_METHOD(thread_icmp_ln195_1_fu_226_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln194_fu_204_p2 );
    sensitive << ( icmp_ln195_fu_210_p2 );
    sensitive << ( add_ln195_fu_220_p2 );

    SC_METHOD(thread_icmp_ln195_fu_210_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln194_fu_204_p2 );
    sensitive << ( instance_byteIOIndex_fu_56 );

    SC_METHOD(thread_icmp_ln206_fu_307_p2);
    sensitive << ( j_0_reg_105 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_icmp_ln211_fu_328_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( offset_assign_9_reg_127 );

    SC_METHOD(thread_icmp_ln224_fu_269_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln194_fu_204_p2 );
    sensitive << ( icmp_ln195_fu_210_p2 );
    sensitive << ( icmp_ln195_1_fu_226_p2 );
    sensitive << ( add_ln224_fu_263_p2 );

    SC_METHOD(thread_icmp_ln231_fu_380_p2);
    sensitive << ( select_ln224_reg_493 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( loop_1_reg_139 );

    SC_METHOD(thread_icmp_ln237_fu_407_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln231_fu_380_p2 );
    sensitive << ( add_ln236_fu_402_p2 );

    SC_METHOD(thread_instance_state_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( instance_state_addr_1_reg_526 );
    sensitive << ( icmp_ln211_fu_328_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( instance_state_addr_reg_549 );
    sensitive << ( icmp_ln231_fu_380_p2 );
    sensitive << ( grp_KeccakP1600_Permute_s_fu_163_state_address0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln149_1_fu_340_p1 );
    sensitive << ( zext_ln149_fu_397_p1 );

    SC_METHOD(thread_instance_state_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln211_fu_328_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln231_fu_380_p2 );
    sensitive << ( grp_KeccakP1600_Permute_s_fu_163_state_ce0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_instance_state_d0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_KeccakP1600_Permute_s_fu_163_state_d0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( xor_ln149_1_fu_367_p2 );
    sensitive << ( xor_ln149_fu_438_p2 );

    SC_METHOD(thread_instance_state_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_KeccakP1600_Permute_s_fu_163_state_we0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_j_5_fu_345_p2);
    sensitive << ( j_0_reg_105 );

    SC_METHOD(thread_j_fu_232_p2);
    sensitive << ( i_22_fu_52 );

    SC_METHOD(thread_loop_40_fu_334_p2);
    sensitive << ( offset_assign_9_reg_127 );

    SC_METHOD(thread_loop_fu_385_p2);
    sensitive << ( loop_1_reg_139 );

    SC_METHOD(thread_p_2_rec_fu_445_p2);
    sensitive << ( p_01_rec_reg_93 );
    sensitive << ( p_1_rec_pn_reg_151 );

    SC_METHOD(thread_partialBlock_1_fu_275_p2);
    sensitive << ( instance_byteIOIndex_fu_56 );

    SC_METHOD(thread_partialBlock_fu_253_p2);
    sensitive << ( trunc_ln223_fu_249_p1 );

    SC_METHOD(thread_select_ln212_fu_360_p3);
    sensitive << ( data_0_read );
    sensitive << ( xor_ln212_fu_355_p2 );

    SC_METHOD(thread_select_ln224_fu_281_p3);
    sensitive << ( zext_ln223_fu_259_p1 );
    sensitive << ( icmp_ln224_fu_269_p2 );
    sensitive << ( partialBlock_1_fu_275_p2 );

    SC_METHOD(thread_select_ln232_fu_431_p3);
    sensitive << ( data_0_read );
    sensitive << ( xor_ln232_fu_426_p2 );

    SC_METHOD(thread_sub_ln216_fu_317_p2);
    sensitive << ( trunc_ln216_fu_313_p1 );

    SC_METHOD(thread_tmp_fu_194_p4);
    sensitive << ( i_22_fu_52 );

    SC_METHOD(thread_trunc_ln195_fu_216_p1);
    sensitive << ( i_22_fu_52 );

    SC_METHOD(thread_trunc_ln212_1_fu_351_p1);
    sensitive << ( offset_assign_9_reg_127 );

    SC_METHOD(thread_trunc_ln212_fu_242_p1);
    sensitive << ( p_01_rec_reg_93 );

    SC_METHOD(thread_trunc_ln216_fu_313_p1);
    sensitive << ( j_0_reg_105 );

    SC_METHOD(thread_trunc_ln223_fu_249_p1);
    sensitive << ( i_22_fu_52 );

    SC_METHOD(thread_trunc_ln232_1_fu_422_p1);
    sensitive << ( loop_1_reg_139 );

    SC_METHOD(thread_trunc_ln232_fu_303_p1);
    sensitive << ( p_01_rec_reg_93 );

    SC_METHOD(thread_xor_ln149_1_fu_367_p2);
    sensitive << ( instance_state_q0 );
    sensitive << ( select_ln212_fu_360_p3 );

    SC_METHOD(thread_xor_ln149_fu_438_p2);
    sensitive << ( instance_state_q0 );
    sensitive << ( select_ln232_fu_431_p3 );

    SC_METHOD(thread_xor_ln212_fu_355_p2);
    sensitive << ( trunc_ln212_reg_488 );
    sensitive << ( trunc_ln212_1_fu_351_p1 );

    SC_METHOD(thread_xor_ln232_fu_426_p2);
    sensitive << ( trunc_ln232_reg_510 );
    sensitive << ( trunc_ln232_1_fu_422_p1 );

    SC_METHOD(thread_zext_ln149_1_fu_340_p1);
    sensitive << ( offset_assign_9_reg_127 );

    SC_METHOD(thread_zext_ln149_fu_397_p1);
    sensitive << ( add_ln232_fu_391_p2 );

    SC_METHOD(thread_zext_ln206_fu_238_p1);
    sensitive << ( j_fu_232_p2 );

    SC_METHOD(thread_zext_ln223_fu_259_p1);
    sensitive << ( partialBlock_fu_253_p2 );

    SC_METHOD(thread_zext_ln229_1_fu_293_p1);
    sensitive << ( select_ln224_fu_281_p3 );

    SC_METHOD(thread_zext_ln229_fu_289_p1);
    sensitive << ( select_ln224_fu_281_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln194_fu_204_p2 );
    sensitive << ( icmp_ln195_fu_210_p2 );
    sensitive << ( icmp_ln195_1_fu_226_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln211_fu_328_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_KeccakP1600_Permute_s_fu_163_ap_done );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln231_fu_380_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln206_fu_307_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln237_fu_407_p2 );

    ap_CS_fsm = "0000000001";
    grp_KeccakP1600_Permute_s_fu_163_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "KeccakWidth1600_Spon_8_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, instance_state_address0, "(port)instance_state_address0");
    sc_trace(mVcdFile, instance_state_ce0, "(port)instance_state_ce0");
    sc_trace(mVcdFile, instance_state_we0, "(port)instance_state_we0");
    sc_trace(mVcdFile, instance_state_d0, "(port)instance_state_d0");
    sc_trace(mVcdFile, instance_state_q0, "(port)instance_state_q0");
    sc_trace(mVcdFile, instance_byteIOIndex_read, "(port)instance_byteIOIndex_read");
    sc_trace(mVcdFile, data_0_read, "(port)data_0_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, zext_ln206_fu_238_p1, "zext_ln206_fu_238_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln194_fu_204_p2, "icmp_ln194_fu_204_p2");
    sc_trace(mVcdFile, icmp_ln195_fu_210_p2, "icmp_ln195_fu_210_p2");
    sc_trace(mVcdFile, icmp_ln195_1_fu_226_p2, "icmp_ln195_1_fu_226_p2");
    sc_trace(mVcdFile, trunc_ln212_fu_242_p1, "trunc_ln212_fu_242_p1");
    sc_trace(mVcdFile, trunc_ln212_reg_488, "trunc_ln212_reg_488");
    sc_trace(mVcdFile, select_ln224_fu_281_p3, "select_ln224_fu_281_p3");
    sc_trace(mVcdFile, select_ln224_reg_493, "select_ln224_reg_493");
    sc_trace(mVcdFile, zext_ln229_fu_289_p1, "zext_ln229_fu_289_p1");
    sc_trace(mVcdFile, zext_ln229_reg_499, "zext_ln229_reg_499");
    sc_trace(mVcdFile, i_fu_297_p2, "i_fu_297_p2");
    sc_trace(mVcdFile, i_reg_505, "i_reg_505");
    sc_trace(mVcdFile, trunc_ln232_fu_303_p1, "trunc_ln232_fu_303_p1");
    sc_trace(mVcdFile, trunc_ln232_reg_510, "trunc_ln232_reg_510");
    sc_trace(mVcdFile, loop_40_fu_334_p2, "loop_40_fu_334_p2");
    sc_trace(mVcdFile, loop_40_reg_521, "loop_40_reg_521");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, instance_state_addr_1_reg_526, "instance_state_addr_1_reg_526");
    sc_trace(mVcdFile, icmp_ln211_fu_328_p2, "icmp_ln211_fu_328_p2");
    sc_trace(mVcdFile, j_5_fu_345_p2, "j_5_fu_345_p2");
    sc_trace(mVcdFile, j_5_reg_531, "j_5_reg_531");
    sc_trace(mVcdFile, add_ln214_fu_374_p2, "add_ln214_fu_374_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_KeccakP1600_Permute_s_fu_163_ap_ready, "grp_KeccakP1600_Permute_s_fu_163_ap_ready");
    sc_trace(mVcdFile, grp_KeccakP1600_Permute_s_fu_163_ap_done, "grp_KeccakP1600_Permute_s_fu_163_ap_done");
    sc_trace(mVcdFile, loop_fu_385_p2, "loop_fu_385_p2");
    sc_trace(mVcdFile, loop_reg_544, "loop_reg_544");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, instance_state_addr_reg_549, "instance_state_addr_reg_549");
    sc_trace(mVcdFile, icmp_ln231_fu_380_p2, "icmp_ln231_fu_380_p2");
    sc_trace(mVcdFile, p_2_rec_fu_445_p2, "p_2_rec_fu_445_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_KeccakP1600_Permute_s_fu_163_ap_start, "grp_KeccakP1600_Permute_s_fu_163_ap_start");
    sc_trace(mVcdFile, grp_KeccakP1600_Permute_s_fu_163_ap_idle, "grp_KeccakP1600_Permute_s_fu_163_ap_idle");
    sc_trace(mVcdFile, grp_KeccakP1600_Permute_s_fu_163_state_address0, "grp_KeccakP1600_Permute_s_fu_163_state_address0");
    sc_trace(mVcdFile, grp_KeccakP1600_Permute_s_fu_163_state_ce0, "grp_KeccakP1600_Permute_s_fu_163_state_ce0");
    sc_trace(mVcdFile, grp_KeccakP1600_Permute_s_fu_163_state_we0, "grp_KeccakP1600_Permute_s_fu_163_state_we0");
    sc_trace(mVcdFile, grp_KeccakP1600_Permute_s_fu_163_state_d0, "grp_KeccakP1600_Permute_s_fu_163_state_d0");
    sc_trace(mVcdFile, p_01_rec_reg_93, "p_01_rec_reg_93");
    sc_trace(mVcdFile, j_0_reg_105, "j_0_reg_105");
    sc_trace(mVcdFile, p_1_rec_reg_115, "p_1_rec_reg_115");
    sc_trace(mVcdFile, offset_assign_9_reg_127, "offset_assign_9_reg_127");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln206_fu_307_p2, "icmp_ln206_fu_307_p2");
    sc_trace(mVcdFile, loop_1_reg_139, "loop_1_reg_139");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, p_1_rec_pn_reg_151, "p_1_rec_pn_reg_151");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, icmp_ln237_fu_407_p2, "icmp_ln237_fu_407_p2");
    sc_trace(mVcdFile, grp_KeccakP1600_Permute_s_fu_163_ap_start_reg, "grp_KeccakP1600_Permute_s_fu_163_ap_start_reg");
    sc_trace(mVcdFile, zext_ln149_1_fu_340_p1, "zext_ln149_1_fu_340_p1");
    sc_trace(mVcdFile, zext_ln149_fu_397_p1, "zext_ln149_fu_397_p1");
    sc_trace(mVcdFile, i_22_fu_52, "i_22_fu_52");
    sc_trace(mVcdFile, sub_ln216_fu_317_p2, "sub_ln216_fu_317_p2");
    sc_trace(mVcdFile, instance_byteIOIndex_fu_56, "instance_byteIOIndex_fu_56");
    sc_trace(mVcdFile, add_ln236_fu_402_p2, "add_ln236_fu_402_p2");
    sc_trace(mVcdFile, xor_ln149_1_fu_367_p2, "xor_ln149_1_fu_367_p2");
    sc_trace(mVcdFile, xor_ln149_fu_438_p2, "xor_ln149_fu_438_p2");
    sc_trace(mVcdFile, tmp_fu_194_p4, "tmp_fu_194_p4");
    sc_trace(mVcdFile, trunc_ln195_fu_216_p1, "trunc_ln195_fu_216_p1");
    sc_trace(mVcdFile, add_ln195_fu_220_p2, "add_ln195_fu_220_p2");
    sc_trace(mVcdFile, j_fu_232_p2, "j_fu_232_p2");
    sc_trace(mVcdFile, trunc_ln223_fu_249_p1, "trunc_ln223_fu_249_p1");
    sc_trace(mVcdFile, partialBlock_fu_253_p2, "partialBlock_fu_253_p2");
    sc_trace(mVcdFile, zext_ln223_fu_259_p1, "zext_ln223_fu_259_p1");
    sc_trace(mVcdFile, add_ln224_fu_263_p2, "add_ln224_fu_263_p2");
    sc_trace(mVcdFile, icmp_ln224_fu_269_p2, "icmp_ln224_fu_269_p2");
    sc_trace(mVcdFile, partialBlock_1_fu_275_p2, "partialBlock_1_fu_275_p2");
    sc_trace(mVcdFile, zext_ln229_1_fu_293_p1, "zext_ln229_1_fu_293_p1");
    sc_trace(mVcdFile, trunc_ln216_fu_313_p1, "trunc_ln216_fu_313_p1");
    sc_trace(mVcdFile, trunc_ln212_1_fu_351_p1, "trunc_ln212_1_fu_351_p1");
    sc_trace(mVcdFile, xor_ln212_fu_355_p2, "xor_ln212_fu_355_p2");
    sc_trace(mVcdFile, select_ln212_fu_360_p3, "select_ln212_fu_360_p3");
    sc_trace(mVcdFile, add_ln232_fu_391_p2, "add_ln232_fu_391_p2");
    sc_trace(mVcdFile, trunc_ln232_1_fu_422_p1, "trunc_ln232_1_fu_422_p1");
    sc_trace(mVcdFile, xor_ln232_fu_426_p2, "xor_ln232_fu_426_p2");
    sc_trace(mVcdFile, select_ln232_fu_431_p3, "select_ln232_fu_431_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

KeccakWidth1600_Spon_8::~KeccakWidth1600_Spon_8() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_KeccakP1600_Permute_s_fu_163;
}

void KeccakWidth1600_Spon_8::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_KeccakP1600_Permute_s_fu_163_ap_start_reg = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln211_fu_328_p2.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln231_fu_380_p2.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln237_fu_407_p2.read())))) {
            grp_KeccakP1600_Permute_s_fu_163_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_KeccakP1600_Permute_s_fu_163_ap_ready.read())) {
            grp_KeccakP1600_Permute_s_fu_163_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln231_fu_380_p2.read()))) {
        i_22_fu_52 = i_reg_505.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln206_fu_307_p2.read()))) {
        i_22_fu_52 = sub_ln216_fu_317_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_22_fu_52 = ap_const_lv34_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln231_fu_380_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln237_fu_407_p2.read()))) {
        instance_byteIOIndex_fu_56 = add_ln236_fu_402_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln206_fu_307_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln231_fu_380_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln237_fu_407_p2.read())))) {
        instance_byteIOIndex_fu_56 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        instance_byteIOIndex_fu_56 = instance_byteIOIndex_read.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(grp_KeccakP1600_Permute_s_fu_163_ap_done.read(), ap_const_logic_1))) {
        j_0_reg_105 = j_5_reg_531.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln194_fu_204_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln195_fu_210_p2.read()) && 
                esl_seteq<1,1,1>(icmp_ln195_1_fu_226_p2.read(), ap_const_lv1_0))) {
        j_0_reg_105 = zext_ln206_fu_238_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        loop_1_reg_139 = loop_reg_544.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                ((esl_seteq<1,1,1>(icmp_ln194_fu_204_p2.read(), ap_const_lv1_1) && 
                  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln195_1_fu_226_p2.read())) || 
                 (esl_seteq<1,1,1>(icmp_ln194_fu_204_p2.read(), ap_const_lv1_1) && 
                  esl_seteq<1,1,1>(icmp_ln195_fu_210_p2.read(), ap_const_lv1_0))))) {
        loop_1_reg_139 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln206_fu_307_p2.read()))) {
        offset_assign_9_reg_127 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        offset_assign_9_reg_127 = loop_40_reg_521.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p_01_rec_reg_93 = p_2_rec_fu_445_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_01_rec_reg_93 = ap_const_lv64_0;
    }
    if (((esl_seteq<1,1,1>(grp_KeccakP1600_Permute_s_fu_163_ap_done.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln231_fu_380_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln237_fu_407_p2.read())))) {
        p_1_rec_pn_reg_151 = zext_ln229_reg_499.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln206_fu_307_p2.read()))) {
        p_1_rec_pn_reg_151 = p_1_rec_reg_115.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(grp_KeccakP1600_Permute_s_fu_163_ap_done.read(), ap_const_logic_1))) {
        p_1_rec_reg_115 = add_ln214_fu_374_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln194_fu_204_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln195_fu_210_p2.read()) && 
                esl_seteq<1,1,1>(icmp_ln195_1_fu_226_p2.read(), ap_const_lv1_0))) {
        p_1_rec_reg_115 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && ((esl_seteq<1,1,1>(icmp_ln194_fu_204_p2.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln195_1_fu_226_p2.read())) || 
  (esl_seteq<1,1,1>(icmp_ln194_fu_204_p2.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(icmp_ln195_fu_210_p2.read(), ap_const_lv1_0))))) {
        i_reg_505 = i_fu_297_p2.read();
        select_ln224_reg_493 = select_ln224_fu_281_p3.read();
        trunc_ln232_reg_510 = trunc_ln232_fu_303_p1.read();
        zext_ln229_reg_499 = zext_ln229_fu_289_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln211_fu_328_p2.read()))) {
        instance_state_addr_1_reg_526 =  (sc_lv<8>) (zext_ln149_1_fu_340_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln231_fu_380_p2.read()))) {
        instance_state_addr_reg_549 =  (sc_lv<8>) (zext_ln149_fu_397_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln211_fu_328_p2.read()))) {
        j_5_reg_531 = j_5_fu_345_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        loop_40_reg_521 = loop_40_fu_334_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        loop_reg_544 = loop_fu_385_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln194_fu_204_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln195_fu_210_p2.read()) && esl_seteq<1,1,1>(icmp_ln195_1_fu_226_p2.read(), ap_const_lv1_0))) {
        trunc_ln212_reg_488 = trunc_ln212_fu_242_p1.read();
    }
}

void KeccakWidth1600_Spon_8::thread_add_ln195_fu_220_p2() {
    add_ln195_fu_220_p2 = (!ap_const_lv30_A8.is_01() || !trunc_ln195_fu_216_p1.read().is_01())? sc_lv<30>(): (sc_biguint<30>(ap_const_lv30_A8) + sc_biguint<30>(trunc_ln195_fu_216_p1.read()));
}

void KeccakWidth1600_Spon_8::thread_add_ln214_fu_374_p2() {
    add_ln214_fu_374_p2 = (!p_1_rec_reg_115.read().is_01() || !ap_const_lv64_A8.is_01())? sc_lv<64>(): (sc_biguint<64>(p_1_rec_reg_115.read()) + sc_biguint<64>(ap_const_lv64_A8));
}

void KeccakWidth1600_Spon_8::thread_add_ln224_fu_263_p2() {
    add_ln224_fu_263_p2 = (!zext_ln223_fu_259_p1.read().is_01() || !instance_byteIOIndex_fu_56.read().is_01())? sc_lv<32>(): (sc_biguint<32>(zext_ln223_fu_259_p1.read()) + sc_biguint<32>(instance_byteIOIndex_fu_56.read()));
}

void KeccakWidth1600_Spon_8::thread_add_ln232_fu_391_p2() {
    add_ln232_fu_391_p2 = (!instance_byteIOIndex_fu_56.read().is_01() || !loop_1_reg_139.read().is_01())? sc_lv<32>(): (sc_biguint<32>(instance_byteIOIndex_fu_56.read()) + sc_biguint<32>(loop_1_reg_139.read()));
}

void KeccakWidth1600_Spon_8::thread_add_ln236_fu_402_p2() {
    add_ln236_fu_402_p2 = (!instance_byteIOIndex_fu_56.read().is_01() || !select_ln224_reg_493.read().is_01())? sc_lv<32>(): (sc_biguint<32>(instance_byteIOIndex_fu_56.read()) + sc_biguint<32>(select_ln224_reg_493.read()));
}

void KeccakWidth1600_Spon_8::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void KeccakWidth1600_Spon_8::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void KeccakWidth1600_Spon_8::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void KeccakWidth1600_Spon_8::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void KeccakWidth1600_Spon_8::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void KeccakWidth1600_Spon_8::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void KeccakWidth1600_Spon_8::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void KeccakWidth1600_Spon_8::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void KeccakWidth1600_Spon_8::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void KeccakWidth1600_Spon_8::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void KeccakWidth1600_Spon_8::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln194_fu_204_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_8::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_8::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln194_fu_204_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_8::thread_ap_return() {
    ap_return = instance_byteIOIndex_fu_56.read();
}

void KeccakWidth1600_Spon_8::thread_grp_KeccakP1600_Permute_s_fu_163_ap_start() {
    grp_KeccakP1600_Permute_s_fu_163_ap_start = grp_KeccakP1600_Permute_s_fu_163_ap_start_reg.read();
}

void KeccakWidth1600_Spon_8::thread_i_fu_297_p2() {
    i_fu_297_p2 = (!zext_ln229_1_fu_293_p1.read().is_01() || !i_22_fu_52.read().is_01())? sc_lv<34>(): (sc_biguint<34>(zext_ln229_1_fu_293_p1.read()) + sc_biguint<34>(i_22_fu_52.read()));
}

void KeccakWidth1600_Spon_8::thread_icmp_ln194_fu_204_p2() {
    icmp_ln194_fu_204_p2 = (!tmp_fu_194_p4.read().is_01() || !ap_const_lv33_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_194_p4.read() == ap_const_lv33_0);
}

void KeccakWidth1600_Spon_8::thread_icmp_ln195_1_fu_226_p2() {
    icmp_ln195_1_fu_226_p2 = (!add_ln195_fu_220_p2.read().is_01() || !ap_const_lv30_2.is_01())? sc_lv<1>(): (sc_biguint<30>(add_ln195_fu_220_p2.read()) > sc_biguint<30>(ap_const_lv30_2));
}

void KeccakWidth1600_Spon_8::thread_icmp_ln195_fu_210_p2() {
    icmp_ln195_fu_210_p2 = (!instance_byteIOIndex_fu_56.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(instance_byteIOIndex_fu_56.read() == ap_const_lv32_0);
}

void KeccakWidth1600_Spon_8::thread_icmp_ln206_fu_307_p2() {
    icmp_ln206_fu_307_p2 = (!j_0_reg_105.read().is_01() || !ap_const_lv64_A8.is_01())? sc_lv<1>(): (sc_biguint<64>(j_0_reg_105.read()) < sc_biguint<64>(ap_const_lv64_A8));
}

void KeccakWidth1600_Spon_8::thread_icmp_ln211_fu_328_p2() {
    icmp_ln211_fu_328_p2 = (!offset_assign_9_reg_127.read().is_01() || !ap_const_lv8_A8.is_01())? sc_lv<1>(): sc_lv<1>(offset_assign_9_reg_127.read() == ap_const_lv8_A8);
}

void KeccakWidth1600_Spon_8::thread_icmp_ln224_fu_269_p2() {
    icmp_ln224_fu_269_p2 = (!add_ln224_fu_263_p2.read().is_01() || !ap_const_lv32_A8.is_01())? sc_lv<1>(): (sc_biguint<32>(add_ln224_fu_263_p2.read()) > sc_biguint<32>(ap_const_lv32_A8));
}

void KeccakWidth1600_Spon_8::thread_icmp_ln231_fu_380_p2() {
    icmp_ln231_fu_380_p2 = (!loop_1_reg_139.read().is_01() || !select_ln224_reg_493.read().is_01())? sc_lv<1>(): sc_lv<1>(loop_1_reg_139.read() == select_ln224_reg_493.read());
}

void KeccakWidth1600_Spon_8::thread_icmp_ln237_fu_407_p2() {
    icmp_ln237_fu_407_p2 = (!add_ln236_fu_402_p2.read().is_01() || !ap_const_lv32_A8.is_01())? sc_lv<1>(): sc_lv<1>(add_ln236_fu_402_p2.read() == ap_const_lv32_A8);
}

void KeccakWidth1600_Spon_8::thread_instance_state_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        instance_state_address0 = instance_state_addr_reg_549.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln231_fu_380_p2.read()))) {
        instance_state_address0 =  (sc_lv<8>) (zext_ln149_fu_397_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        instance_state_address0 = instance_state_addr_1_reg_526.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln211_fu_328_p2.read()))) {
        instance_state_address0 =  (sc_lv<8>) (zext_ln149_1_fu_340_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        instance_state_address0 = grp_KeccakP1600_Permute_s_fu_163_state_address0.read();
    } else {
        instance_state_address0 = "XXXXXXXX";
    }
}

void KeccakWidth1600_Spon_8::thread_instance_state_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln211_fu_328_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln231_fu_380_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        instance_state_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        instance_state_ce0 = grp_KeccakP1600_Permute_s_fu_163_state_ce0.read();
    } else {
        instance_state_ce0 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_8::thread_instance_state_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        instance_state_d0 = xor_ln149_fu_438_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        instance_state_d0 = xor_ln149_1_fu_367_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        instance_state_d0 = grp_KeccakP1600_Permute_s_fu_163_state_d0.read();
    } else {
        instance_state_d0 = "XXXXXXXX";
    }
}

void KeccakWidth1600_Spon_8::thread_instance_state_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        instance_state_we0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        instance_state_we0 = grp_KeccakP1600_Permute_s_fu_163_state_we0.read();
    } else {
        instance_state_we0 = ap_const_logic_0;
    }
}

void KeccakWidth1600_Spon_8::thread_j_5_fu_345_p2() {
    j_5_fu_345_p2 = (!j_0_reg_105.read().is_01() || !ap_const_lv64_FFFFFFFFFFFFFF58.is_01())? sc_lv<64>(): (sc_biguint<64>(j_0_reg_105.read()) + sc_bigint<64>(ap_const_lv64_FFFFFFFFFFFFFF58));
}

void KeccakWidth1600_Spon_8::thread_j_fu_232_p2() {
    j_fu_232_p2 = (!ap_const_lv34_2.is_01() || !i_22_fu_52.read().is_01())? sc_lv<34>(): (sc_biguint<34>(ap_const_lv34_2) - sc_biguint<34>(i_22_fu_52.read()));
}

void KeccakWidth1600_Spon_8::thread_loop_40_fu_334_p2() {
    loop_40_fu_334_p2 = (!offset_assign_9_reg_127.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(offset_assign_9_reg_127.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void KeccakWidth1600_Spon_8::thread_loop_fu_385_p2() {
    loop_fu_385_p2 = (!loop_1_reg_139.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(loop_1_reg_139.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void KeccakWidth1600_Spon_8::thread_p_2_rec_fu_445_p2() {
    p_2_rec_fu_445_p2 = (!p_1_rec_pn_reg_151.read().is_01() || !p_01_rec_reg_93.read().is_01())? sc_lv<64>(): (sc_biguint<64>(p_1_rec_pn_reg_151.read()) + sc_biguint<64>(p_01_rec_reg_93.read()));
}

void KeccakWidth1600_Spon_8::thread_partialBlock_1_fu_275_p2() {
    partialBlock_1_fu_275_p2 = (!ap_const_lv32_A8.is_01() || !instance_byteIOIndex_fu_56.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_A8) - sc_biguint<32>(instance_byteIOIndex_fu_56.read()));
}

void KeccakWidth1600_Spon_8::thread_partialBlock_fu_253_p2() {
    partialBlock_fu_253_p2 = (!ap_const_lv2_2.is_01() || !trunc_ln223_fu_249_p1.read().is_01())? sc_lv<2>(): (sc_bigint<2>(ap_const_lv2_2) - sc_biguint<2>(trunc_ln223_fu_249_p1.read()));
}

void KeccakWidth1600_Spon_8::thread_select_ln212_fu_360_p3() {
    select_ln212_fu_360_p3 = (!xor_ln212_fu_355_p2.read()[0].is_01())? sc_lv<8>(): ((xor_ln212_fu_355_p2.read()[0].to_bool())? ap_const_lv8_0: data_0_read.read());
}

void KeccakWidth1600_Spon_8::thread_select_ln224_fu_281_p3() {
    select_ln224_fu_281_p3 = (!icmp_ln224_fu_269_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln224_fu_269_p2.read()[0].to_bool())? partialBlock_1_fu_275_p2.read(): zext_ln223_fu_259_p1.read());
}

void KeccakWidth1600_Spon_8::thread_select_ln232_fu_431_p3() {
    select_ln232_fu_431_p3 = (!xor_ln232_fu_426_p2.read()[0].is_01())? sc_lv<8>(): ((xor_ln232_fu_426_p2.read()[0].to_bool())? ap_const_lv8_0: data_0_read.read());
}

void KeccakWidth1600_Spon_8::thread_sub_ln216_fu_317_p2() {
    sub_ln216_fu_317_p2 = (!ap_const_lv34_2.is_01() || !trunc_ln216_fu_313_p1.read().is_01())? sc_lv<34>(): (sc_biguint<34>(ap_const_lv34_2) - sc_biguint<34>(trunc_ln216_fu_313_p1.read()));
}

void KeccakWidth1600_Spon_8::thread_tmp_fu_194_p4() {
    tmp_fu_194_p4 = i_22_fu_52.read().range(33, 1);
}

void KeccakWidth1600_Spon_8::thread_trunc_ln195_fu_216_p1() {
    trunc_ln195_fu_216_p1 = i_22_fu_52.read().range(30-1, 0);
}

void KeccakWidth1600_Spon_8::thread_trunc_ln212_1_fu_351_p1() {
    trunc_ln212_1_fu_351_p1 = offset_assign_9_reg_127.read().range(1-1, 0);
}

void KeccakWidth1600_Spon_8::thread_trunc_ln212_fu_242_p1() {
    trunc_ln212_fu_242_p1 = p_01_rec_reg_93.read().range(1-1, 0);
}

void KeccakWidth1600_Spon_8::thread_trunc_ln216_fu_313_p1() {
    trunc_ln216_fu_313_p1 = j_0_reg_105.read().range(34-1, 0);
}

void KeccakWidth1600_Spon_8::thread_trunc_ln223_fu_249_p1() {
    trunc_ln223_fu_249_p1 = i_22_fu_52.read().range(2-1, 0);
}

void KeccakWidth1600_Spon_8::thread_trunc_ln232_1_fu_422_p1() {
    trunc_ln232_1_fu_422_p1 = loop_1_reg_139.read().range(1-1, 0);
}

void KeccakWidth1600_Spon_8::thread_trunc_ln232_fu_303_p1() {
    trunc_ln232_fu_303_p1 = p_01_rec_reg_93.read().range(1-1, 0);
}

void KeccakWidth1600_Spon_8::thread_xor_ln149_1_fu_367_p2() {
    xor_ln149_1_fu_367_p2 = (instance_state_q0.read() ^ select_ln212_fu_360_p3.read());
}

void KeccakWidth1600_Spon_8::thread_xor_ln149_fu_438_p2() {
    xor_ln149_fu_438_p2 = (instance_state_q0.read() ^ select_ln232_fu_431_p3.read());
}

void KeccakWidth1600_Spon_8::thread_xor_ln212_fu_355_p2() {
    xor_ln212_fu_355_p2 = (trunc_ln212_reg_488.read() ^ trunc_ln212_1_fu_351_p1.read());
}

void KeccakWidth1600_Spon_8::thread_xor_ln232_fu_426_p2() {
    xor_ln232_fu_426_p2 = (trunc_ln232_1_fu_422_p1.read() ^ trunc_ln232_reg_510.read());
}

void KeccakWidth1600_Spon_8::thread_zext_ln149_1_fu_340_p1() {
    zext_ln149_1_fu_340_p1 = esl_zext<64,8>(offset_assign_9_reg_127.read());
}

void KeccakWidth1600_Spon_8::thread_zext_ln149_fu_397_p1() {
    zext_ln149_fu_397_p1 = esl_zext<64,32>(add_ln232_fu_391_p2.read());
}

void KeccakWidth1600_Spon_8::thread_zext_ln206_fu_238_p1() {
    zext_ln206_fu_238_p1 = esl_zext<64,34>(j_fu_232_p2.read());
}

void KeccakWidth1600_Spon_8::thread_zext_ln223_fu_259_p1() {
    zext_ln223_fu_259_p1 = esl_zext<32,2>(partialBlock_fu_253_p2.read());
}

void KeccakWidth1600_Spon_8::thread_zext_ln229_1_fu_293_p1() {
    zext_ln229_1_fu_293_p1 = esl_zext<34,32>(select_ln224_fu_281_p3.read());
}

void KeccakWidth1600_Spon_8::thread_zext_ln229_fu_289_p1() {
    zext_ln229_fu_289_p1 = esl_zext<64,32>(select_ln224_fu_281_p3.read());
}

void KeccakWidth1600_Spon_8::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln194_fu_204_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && ((esl_seteq<1,1,1>(icmp_ln194_fu_204_p2.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln195_1_fu_226_p2.read())) || 
  (esl_seteq<1,1,1>(icmp_ln194_fu_204_p2.read(), ap_const_lv1_1) && 
   esl_seteq<1,1,1>(icmp_ln195_fu_210_p2.read(), ap_const_lv1_0))))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln206_fu_307_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln211_fu_328_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(grp_KeccakP1600_Permute_s_fu_163_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln231_fu_380_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln237_fu_407_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln231_fu_380_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln237_fu_407_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(grp_KeccakP1600_Permute_s_fu_163_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<10>) ("XXXXXXXXXX");
            break;
    }
}

}

